#!/usr/bin/env bash
# Pick a window open/close shader and apply it live.
# Usage: pick.sh            -> rofi menu
#        pick.sh <name>     -> apply directly (name = folder in shaders/, or "off")
set -euo pipefail

dir="$HOME/.config/niri/shaders"
out="$dir/active.kdl"
shader_ms="${SHADER_MS:-500}"   # playback time while a shader is active

if [ $# -ge 1 ]; then
    choice="$1"
else
    choice=$( { echo off; find "$dir" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort; } \
              | rofi -dmenu -i -p "window shader") || exit 0
    [ -n "$choice" ] || exit 0
fi

if [ "$choice" = "off" ]; then
    echo '// generated by pick.sh -- no shader active' > "$out"
    notify-send -a niri "Window shader" "off" 2>/dev/null || true
    exit 0
fi

[ -d "$dir/$choice" ] || { notify-send -u critical -a niri "Window shader" "unknown: $choice"; exit 1; }

python3 - "$dir" "$choice" "$out" "$shader_ms" <<'PY'
import sys
from pathlib import Path

d, name, out, ms = Path(sys.argv[1]), sys.argv[2], Path(sys.argv[3]), sys.argv[4]
lines = ["// generated by pick.sh -- select a shader with Mod+Shift+S", "animations {"]
for side in ("open", "close"):
    f = d / name / f"{side}.glsl"
    if not f.exists():
        continue
    src = f.read_text()
    assert '"#' not in src, f"{f}: cannot embed in KDL raw string"
    lines += [
        f"    window-{side} {{",
        f"        duration-ms {ms}",
        '        curve "linear"',
        f'        custom-shader r#"{src}"#',
        "    }",
    ]
lines.append("}")
out.write_text("\n".join(lines) + "\n")
PY

notify-send -a niri "Window shader" "$choice" 2>/dev/null || true
