#!/usr/bin/env bash
# Quick select a window open/close shader and apply it live.
# Usage: qs.sh            -> fzf menu
#        qs.sh <name>     -> apply directly (name = folder in shaders/, or "off")
set -euo pipefail

dir="$HOME/.config/niri/shaders"
out="$dir/active.kdl"
shader_ms="${SHADER_MS:-500}"   # playback time while a shader is active

if [ $# -ge 1 ]; then
    choice="$1"
else
    if [ "${QS_IN_FOOT:-0}" != 1 ]; then
        # open the menu in a foot terminal
        foot --app-id=qsshaders -- sh -c 'QS_IN_FOOT=1 exec "$0"' "$0"
        exit 0
    fi
    choice=$( { echo off; find "$dir" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort; } \
              | fzf --prompt="shader > " \
                    --preview="if [ {} = off ]; then echo 'disable shader'; else cat '$dir'/{}'/config' 2>/dev/null || echo '(no config)'; fi" \
                    --preview-window=right:30%:wrap) || exit 0
    [ -n "$choice" ] || exit 0
fi

if [ "$choice" = "off" ]; then
    echo '// generated by qs.sh -- no shader active' > "$out"
    notify-send -a niri "Window shader" "off" 2>/dev/null || true
    exit 0
fi

[ -d "$dir/$choice" ] || { notify-send -u critical -a niri "Window shader" "unknown: $choice"; exit 1; }

python3 - "$dir" "$choice" "$out" "$shader_ms" <<'PY'
import sys
from pathlib import Path

d, name, out, ms = Path(sys.argv[1]), sys.argv[2], Path(sys.argv[3]), sys.argv[4]
lines = ["// generated by qs.sh -- select a shader with Mod+Shift+S", "animations {"]
for side in ("open", "close"):
    f = d / name / f"{side}.glsl"
    if not f.exists():
        continue
    src = f.read_text()
    assert '"#' not in src, f"{f}: cannot embed in KDL raw string"
    lines += [
        f"    window-{side} {{",
        f"        duration-ms {ms}",
        '        curve "linear"',
        f'        custom-shader r#"{src}"#',
        "    }",
    ]
lines.append("}")
out.write_text("\n".join(lines) + "\n")
PY

notify-send -a niri "Window shader" "$choice" 2>/dev/null || true