foreground              #f0eff1
background              #34294f
selection_foreground    #171423
selection_background    #fefe60

cursor                  #36f9f6
cursor_text_color       #171423

url_color               #f28705

active_border_color     #36f9f6
inactive_border_color   #463465
bell_border_color       #fe4450

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #171423
active_tab_background   #2de2e6
inactive_tab_foreground #848bbd
inactive_tab_background #34294f
tab_bar_background      #171423

mark1_foreground #171423
mark1_background #36f9f6
mark2_foreground #171423
mark2_background #72f1b8
mark3_foreground #171423
mark3_background #f28705

color0 #463465
color8 #a9b1d6

color1 #fe4450
color9 #fe4450

color2  #36f9f6
color10 #2de2e6

color3  #f28705
color11 #ff7edb

color4  #72f1b8
color12 #fefe60

color5  #2de2e6
color13 #ff7edb

color6  #fefe60
color14 #ff7edb

color7  #848bbd
color15 #f0eff1
