# Location: ~/.config/matugen/templates/kitty.conf
cursor_trail 1
cursor_trail_decay 0.1 0.4
# Font
font_family      Departure Mono
font_size        11.5

# Window Padding
window_padding_width 30

# Colors & Transparency
background_opacity 0.4
background         #101417
foreground         #e0e3e8

# Terminal Colors
color0 #76777a
color1 #ff897d
color2 #5bb3f0
color3 #b4a5cb
color4 #9cadbd
color5 #3b98d3
color6 #998ab0
color7 #e0e3e8

color8  #8b9198
color9  #ffdad6
color10 #cae6ff
color11 #ebdcff
color12 #d3e5f6
color13 #e6f2ff
color14 #f7edff
color15 #363a3e

# Cursor Customization
cursor                 #e0e3e8
cursor_text_color      #101417
cursor_shape           block
cursor_blink_interval  0.5

# Keybindings
map alt+up   scroll_page_up
map alt+down scroll_page_down
map alt+c    copy_to_clipboard
map alt+v    paste_from_clipboard
