foreground            #dce3e9
background            #0d1418
selection_foreground  #3a3000
selection_background  #dec663
url_color             #97ceec
cursor                #dec663
cursor_text_color     #3a3000

color0   #0d1418
color1   #ffb4ab
color2   #dec663
color3   #97ceec
color4   #dec663
color5   #97ceec
color6   #064c66
color7   #dce3e9

color8   #85939b
color9   #ffb4ab
color10  #dec663
color11  #97ceec
color12  #dec663
color13  #97ceec
color14  #064c66
color15  #dce3e9

tab_bar_background              #0d1418
tab_bar_margin_color            #0d1418
active_tab_foreground           #3a3000
active_tab_background           #dec663
inactive_tab_foreground         #bbc8d2
inactive_tab_background         #0d1418
