background #10140f
foreground #e0e4db

cursor #a1d39a
cursor_text_color #0a390f

selection_background #245024
selection_foreground #e0e4db

# regular (0-7)
color0  #767873
color1  #ff897d
color2  #56c159
color3  #86b3b8
color4  #9fb099
color5  #39a541
color6  #6b989d
color7  #e0e4db

# bright (8-15)
color8  #8c9388
color9  #ffdad6
color10 #8efb8a
color11 #bcebf0
color12 #d5e8ce
color13 #c8ffbf
color14 #caf9ff
color15 #363a34
