background #14140c
foreground #e6e3d5

cursor #cbcb76
cursor_text_color #323200

selection_background #494900
selection_foreground #e6e3d5

# regular (0-7)
color0  #797770
color1  #ff897d
color2  #afb03f
color3  #89b4a2
color4  #aead8b
color5  #959525
color6  #6f9a88
color7  #e6e3d5

# bright (8-15)
color8  #939182
color9  #ffdad6
color10 #e8e970
color11 #bfecd9
color12 #e6e4bf
color13 #f6f77d
color14 #cdfbe7
color15 #3a3a30
