[general]
bars = 16
framerate = 30
autosens = 1
sensitivity = 60
sleep_timer = 5

[input]
method = pipewire
source = auto
channels = 2

[output]
method = raw
data_format = ascii
ascii_max_range = 1000
bar_delimiter = 59
frame_delimiter = 10
channels = mono
mono_option = average

[smoothing]
noise_reduction = 77

[eq]
1 = 1.0
2 = 0.9
3 = 1.0
4 = 1.1
5 = 1.0