
[config]
# Adjust contrast from -1.0 to 1.0
contrast = 0.5
# Fallback if image extraction fails
[config.wallpaper]
# Automatically set wallpaper using a command
set = true
command = "awww img {{ image }}"
 [templates.niri]
input_path = '~/.config/matugen/templates/config.kdl'
output_path = '~/.config/niri/borders.kdl'
[templates.foot]
input_path = '/home/karasu/.config/matugen/templates/foot.ini'
output_path = '/home/karasu/.config/foot/foot.ini'
[templates.firefox_colors]
input_path = '~/.config/matugen/templates/firefox-colors.css'
output_path = '~/.librewolf/fuoz9ly2.default-default/chrome/colors.css'
# ...
[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'
[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/theme.conf'
[templates.telegram-tdesktop-theme]
input_path = '~/.config/matugen/templates/telegram-tdesktop-theme.tdesktop-theme'
output_path = '~/.config/telegram/tdesktop-theme.tdesktop-theme'
[templates.swaync]
input_path = "~/.config/matugen/templates/swaync-colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -rs"
# ...
[templates.television]
input_path = '~/.config/matugen/templates/television.toml'
output_path = '~/.config/television/themes/matugen.toml'
# ...
[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-3.0.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-4.0.css"
output_path = "~/.config/gtk-4.0/gtk.css"
