# Location: ~/.config/matugen/templates/foot.ini


[colors-dark]
alpha=0.67
foreground=efdee0
background=191113

## Normal/Regular Colors (0-7)
regular0=3c3234 # black
regular1=ffb4ab                     # red
regular2=ffb1c1                   # green
regular3=ecbe91                  # yellow
regular4=713342         # blue
regular5=e4bdc3                 # magenta
regular6=5b3f44       # cyan
regular7=3c3234                # white

## Bright Colors (8-15)
bright0=9f8c8f                    # bright black
bright1=93000a            # bright red
bright2=ffb1c1                    # bright green
bright3=60401d         # bright yellow
bright4=8d4959            # bright blue
bright5=5b3f44        # bright magenta
bright6=524345            # bright cyan
bright7=382e2f         # bright white

## Miscellaneous colors
selection-foreground=ffd9df
selection-background=713342
urls=ecbe91
