# Location: ~/.config/matugen/templates/foot.ini


[main]
font= Departure Mono:style:size=10
pad = 30x30
[colors-dark]
alpha=0.4
background=0f1417
foreground=dee3e6

regular0=757779
regular1=ff897d
regular2=3eb8e2
regular3=a9a7ce
regular4=99afba
regular5=009dc5
regular6=8f8db2
regular7=dee3e6

bright0=8a9296
bright1=ffdad6
bright2=bbe9ff
bright3=e2dfff
bright4=cfe6f2
bright5=dff4ff
bright6=f2efff
bright7=353a3d
[key-bindings]
scrollback-up-page=Alt+Up
scrollback-down-page=Alt+Down
clipboard-copy=Alt+c
clipboard-paste=Alt+v
