# Location: ~/.config/matugen/templates/foot.ini


[main]
font= Departure Mono:style:size=9.5
pad = 30x30
[colors-dark]
alpha=0.4
background=101417
foreground=e0e3e8

regular0=76777a
regular1=ff897d
regular2=5bb3f0
regular3=b4a5cb
regular4=9cadbd
regular5=3b98d3
regular6=998ab0
regular7=e0e3e8

bright0=8b9198
bright1=ffdad6
bright2=cae6ff
bright3=ebdcff
bright4=d3e5f6
bright5=e6f2ff
bright6=f7edff
bright7=363a3e
[key-bindings]
scrollback-up-page=Alt+Up
scrollback-down-page=Alt+Down
clipboard-copy=Alt+c
clipboard-paste=Alt+v
