font= Departure Mono:style=regular:size=12

[main]
pad = 20x30
# 
 [colors-dark]
 alpha=0.8
 background = 21222c

 
 regular0 = 21222c
 regular1 = c197fd
 regular2 = 50fa7b
 regular3 = f7c346
 regular4 = bd93f9
 regular5 = ff79c6
 regular6 = 8be9fd
 regular7 = f8f8f2
 
 bright0  = 6272a4
 bright1  = ff6e6e
 bright2  = 69ff94
 bright3  = f4c346
 bright4  = d6acff
 bright5  = ff92df
 bright7  = ffffff
 
 selection-foreground = f8f8f2
 selection-background = 44475a
 
 
# [colors-light]
# alpha=0.95

# 
# foreground = 2e2e2e
# background = ffffff
# 
# regular0 = 000000
# regular1 = cc0000
# regular2 = 4e9a06
# regular3 = c4a000
# regular4 = 3465a4
# regular5 = 75507b
# regular6 = 06989a
# regular7 = d3d7cf
# 
# bright0  = 555753
# bright1  = ef2929
# bright2  = 8ae234
# bright3  = fce94f
# bright4  = 729fcf
# bright5  = ad7fa8
# bright6  = 34e2e2
# bright7  = eeeeec
# 
# selection-foreground = ffffff
# selection-background = 4a90e2
# [colors-dark]
# # The basic colors
# foreground=cdd6f4
# background=1e1e2e
# 
# alpha=0.70
# # Selection colors
# selection-foreground=1e1e2e
# selection-background=f5e0dc
# 
# # Cursor colors
# 
# # URL underline color
# urls=b4befe
# 
# # The 16 terminal colors
# 
# ## black
# regular0=43465a
# bright0=43465a
# 
# ## red
# regular1=f38ba8
# bright1=f38ba8
# 
# ## green
# regular2=a6e3a1
# bright2=a6e3a1
# 
# ## yellow
# regular3=f9e2af
# bright3=f9e2af
# 
# ## blue
# regular4=87b0f9
# bright4=87b0f9
# 
# ## magenta
# regular5=f5c2e7
# bright5=f5c2e7
# 
# ## cyan
# regular6=94e2d5
# bright6=94e2d5
# 
# # 
[key-bindings]
scrollback-up-page=Alt+Up
scrollback-down-page=Alt+Down
clipboard-copy=Alt+c
clipboard-paste=Alt+v

