-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            noise = 0.008,
            passes = 3,
            size = 7,
            xray = true,
        },
        dim_around = 0.55,
        dim_inactive = true,
        dim_strength = 0.15,
        rounding = 20,
        rounding_power = 3.1,
        shadow = {
            range = 9,
            render_power = 4,
        },
    },
    general = {
        allow_tearing = true,
        gaps_in = 7,
        gaps_out = 13,
        layout = "scrolling",
    },
    input = {
        repeat_delay = 238,
        repeat_rate = 107,
    },
    misc = {
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
        vrr = 1,
    },
    xwayland = {
        force_zero_scaling = true,
    },
})

-- Monitors
hl.monitor({
    output = "desc:BOE 0x0700",
    mode = "1920x1080@60.03Hz",
    position = "0x0",
    scale = 0.83,
    cm = "srgb",
})
