[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on   = ["c", "i"]
run  = "plugin sxiv"
desc = "Preview images in sxiv"

[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on   = ["c", "w"]
run  = 'shell --orphan "awww img %s && matugen image %s --type scheme-tonal-spot --prefer lightness"'
desc = "Set wallpaper and generate palette"
