# Location: ~/.config/matugen/templates/foot.ini


[main]
font= Departure Mono:style:size=10
pad = 30x30

[colors-dark]
alpha=1.0
background={{colors.surface.dark.hex_stripped}}
foreground={{colors.on_surface.dark.hex_stripped}}

selection-background={{colors.secondary_container.dark.hex_stripped}}
selection-foreground={{colors.on_secondary_container.dark.hex_stripped}}

regular0={{colors.surface_container.dark.hex_stripped}}
regular1={{colors.error.dark.hex_stripped}}
regular2={{colors.primary.dark.hex_stripped}}
regular3={{colors.secondary.dark.hex_stripped}}
regular4={{colors.primary_fixed_dim.dark.hex_stripped}}
regular5={{colors.tertiary.dark.hex_stripped}}
regular6={{colors.inverse_primary.dark.hex_stripped}}
regular7={{colors.on_surface_variant.dark.hex_stripped}}

bright0={{colors.surface_container_high.dark.hex_stripped}}
bright1={{colors.error_container.dark.hex_stripped}}
bright2={{colors.primary_container.dark.hex_stripped}}
bright3={{colors.secondary_container.dark.hex_stripped}}
bright4={{colors.primary_fixed.dark.hex_stripped}}
bright5={{colors.tertiary_container.dark.hex_stripped}}
bright6={{colors.on_primary_fixed.dark.hex_stripped}}
bright7={{colors.on_surface.dark.hex_stripped}}

dim0={{colors.surface_container_lowest.dark.hex_stripped}}
dim1={{colors.shadow.dark.hex_stripped}}
dim2={{colors.on_surface_variant.dark.hex_stripped}}
dim3={{colors.on_surface.dark.hex_stripped}}
dim4={{colors.outline_variant.dark.hex_stripped}}
dim5={{colors.inverse_primary.dark.hex_stripped}}
dim6={{colors.scrim.dark.hex_stripped}}
dim7={{colors.outline.dark.hex_stripped}}

search-box-match={{colors.on_primary_container.dark.hex_stripped}} {{colors.primary.dark.hex_stripped}}
search-box-no-match={{colors.on_error_container.dark.hex_stripped}} {{colors.error.dark.hex_stripped}}

scrollback-indicator={{colors.on_surface_variant.dark.hex_stripped}} {{colors.surface_container_high.dark.hex_stripped}}

jump-labels={{colors.on_surface.dark.hex_stripped}} {{colors.surface_container_low.dark.hex_stripped}}

cursor={{colors.on_primary.dark.hex_stripped}} {{colors.primary.dark.hex_stripped}}

[key-bindings]
scrollback-up-page=Alt+Up
scrollback-down-page=Alt+Down
clipboard-copy=Alt+c
clipboard-paste=Alt+v

[cursor]
style=beam
blink=yes
