$wallpaper                  = {{ image }}
$foreground                 = rgb({{colors.on_surface.default.hex_stripped}})
$foreground-alt             = rgba({{colors.on_surface_variant.default.hex_stripped}}4D)
$fail                       = rgb({{colors.error.default.hex_stripped}})
